#!/bin/bash

set -ve

set +x

# Workaround for travis-ci/travis-ci#8973
python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

xcodebuild -version | head -n 1 | cut -d ' ' -f 2

id

# See https://mac.r-project.org/openmp/
omp=openmp-7.1.0-darwin17-Release.tar.gz
curl -O https://mac.r-project.org/openmp/$omp
sudo gtar --no-overwrite-dir --owner=travis --group=staff -zxf $omp -C /
rm -r $omp

echo '
#include <stdlib.h>
#include <stdio.h>
#include <omp.h>

int main() {
  #pragma omp parallel num_threads(4)
  {
    printf("Hello from thread %d, nthreads %d\n", omp_get_thread_num(), omp_get_num_threads());
  }
  return EXIT_SUCCESS;
}
' > omptest.c

clang -Xclang -fopenmp -lomp omptest.c -o omptest
./omptest

mkdir -p ~/.R
cp tools/travis/llvm.conf ~/.R/Makevars

R --no-save -f util/update-dependencies.R --args ./DESCRIPTION.in
