require(OpenMx)

A <- mxMatrix(values = runif(25), nrow = 5, ncol = 5, name = 'A')
B <- mxMatrix(values = runif(25), nrow = 5, ncol = 5, name = 'B')
C <- mxAlgebra(sum(A,B), name = 'C')
D <- mxAlgebra(prod(A,B), name = 'D')
E <- mxAlgebra(max(A,B), name = 'E')
F <- mxAlgebra(min(A,B), name = 'F')
G <- mxAlgebra(abs(A), name = 'G')
H <- mxAlgebra(cos(A), name = 'H')
I <- mxAlgebra(cosh(A), name = 'I')
J <- mxAlgebra(sin(A), name = 'J')
K <- mxAlgebra(sinh(A), name = 'K')
L <- mxAlgebra(tan(A), name = 'L')
M <- mxAlgebra(tanh(A), name = 'M')

model <- mxModel(A,B,C,D,E,F,G,H,I,J,K,L,M)

model <- mxRun(model)

omxCheckCloseEnough(model[['C']]@result, sum(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['D']]@result, prod(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['E']]@result, max(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['F']]@result, min(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['G']]@result, abs(A@values), 0.001)
omxCheckCloseEnough(model[['H']]@result, cos(A@values), 0.001)
omxCheckCloseEnough(model[['I']]@result, cosh(A@values), 0.001)
omxCheckCloseEnough(model[['J']]@result, sin(A@values), 0.001)
omxCheckCloseEnough(model[['K']]@result, sinh(A@values), 0.001)
omxCheckCloseEnough(model[['L']]@result, tan(A@values), 0.001)
omxCheckCloseEnough(model[['M']]@result, tanh(A@values), 0.001)
