#!/bin/bash

set -x
set -o errexit

if [ "$TRAVIS_OS_NAME" != "osx" ]; then exit; fi

dhost=travis@vps242190.vps.ovh.ca
ddir=/var/www/html/
ext=tar.gz

scp -v -i /tmp/deploy_rsa -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o CheckHostIP=no staging/OpenMx_*.$ext $dhost:$ddir
ssh -v -i /tmp/deploy_rsa -o PreferredAuthentications=publickey -o StrictHostKeyChecking=no -o CheckHostIP=no $dhost "cd $ddir"' && ln -sf $(ls -t | head -1) OpenMx_latest.'$ext
