#!/bin/bash

set -x
set -o errexit

if [ "$TRAVIS_OS_NAME" != "osx" ]; then exit; fi

dhost=jpritikinlocal@openmx.psyc.virginia.edu
ddir=/var/openmx/OpenMx2/packages/bin/macosx/travis/

scp build/OpenMx_*.tgz $dhost:$ddir
ssh $dhost "cd $ddir"' && ln -sf $(ls -t | head -1) OpenMx_latest.tgz'
