#!/bin/bash

set -ve

#command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
rvm get stable

# Workaround for travis-ci/travis-ci#8973
python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

cp ./util/gcc.conf ~/.R/Makevars

xcodebuild -version | head -n 1 | cut -d ' ' -f 2

# for macos 10.11 :

curl -Lo /tmp/gcc.tar.gz 'http://prdownloads.sourceforge.net/hpc/gcc-5.3-bin.tar.gz?download'
curl -Lo /tmp/gfort.tar.gz 'http://prdownloads.sourceforge.net/hpc/gfortran-5.3-bin.tar.gz?download'

sudo rm -rf /usr/local/lib/gcc
sudo rm -rf /usr/local/include/c++

sudo tar -zxf /tmp/gcc.tar.gz -C /

echo "gcc installed"

sudo tar -zxf /tmp/gfort.tar.gz -C /

echo "gfort installed"

brew install netcdf

echo "netcdf installed"

curl -L https://github.com/Unidata/netcdf-cxx4/archive/v4.3.0.tar.gz | tar -C /tmp --extract --gunzip --file -
(cd /tmp/netcdf-cxx4-4.3.0 && ./configure && sudo make install)

R --no-save -f util/update-dependencies.R --args ./DESCRIPTION.in

which otool
