#!/bin/bash

set -ve

cp ./util/gcc6.conf ~/.R/Makevars

sudo apt-get install -yq --no-install-suggests --no-install-recommends r-cran-digest r-cran-rcpp r-cran-rcppeigen r-cran-stanheaders r-cran-bh r-cran-rpf r-cran-mvtnorm r-cran-numderiv r-cran-roxygen2 r-cran-snowfall r-cran-lme4
