#!/bin/bash

set -ve

# Workaround for travis-ci/travis-ci#8973
python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

cp ./util/gcc.conf ~/.R/Makevars

xcodebuild -version | head -n 1 | cut -d ' ' -f 2

sudo rm -rf /usr/local/lib/gcc
sudo rm -rf /usr/local/include/c++

# for macos 10.11 :

curl -Lo /tmp/gcc.tar.gz 'https://sourceforge.net/projects/hpc/files/hpc/gcc/gcc-7.1-bin.tar.gz/download'
curl -Lo /tmp/gfort.tar.gz 'https://sourceforge.net/projects/hpc/files/hpc/g95/gfortran-7.1-bin.tar.gz/download'

sudo tar -zxf /tmp/gcc.tar.gz -C /
sudo tar -zxf /tmp/gfort.tar.gz -C /

curl -L https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/src/hdf5-1.8.20.tar.bz2 | tar -C /tmp --extract --bzip2 --file -
(cd /tmp/hdf5-1.8.20 && CC=gcc CXX=g++ ./configure --prefix=/usr/local --enable-shared --disable-static && sudo make install 2>/dev/null)

curl -L ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz | tar -C /tmp --extract --gunzip --file -
(cd /tmp/netcdf-4.3.3.1 && CC=gcc ./configure && sudo make install 2>/dev/null)

R --no-save -f util/update-dependencies.R --args ./DESCRIPTION.in

which otool
