#!/bin/bash

set -ve

fold_start() {
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
}

fold_end() {
  echo -e "\ntravis_fold:end:$1\r"
}

# Workaround for travis-ci/travis-ci#8973
python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"

cp ./util/gcc.conf ~/.R/Makevars

xcodebuild -version | head -n 1 | cut -d ' ' -f 2

sudo rm -rf /usr/local/lib/gcc
sudo rm -rf /usr/local/include/c++

# for macos 10.11 :

curl -Lo /tmp/gcc.tar.gz 'https://sourceforge.net/projects/hpc/files/hpc/gcc/gcc-5.3-bin.tar.gz/download'
curl -Lo /tmp/gfort.tar.gz 'https://sourceforge.net/projects/hpc/files/hpc/g95/gfortran-5.3-bin.tar.gz/download'

sudo tar -zxf /tmp/gcc.tar.gz -C /
sudo tar -zxf /tmp/gfort.tar.gz -C /

fold_start hdf5 hdf5
curl -L https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/src/hdf5-1.8.20.tar.bz2 | tar -C /tmp --extract --bzip2 --file -
(cd /tmp/hdf5-1.8.20 && CC=gcc CXX=g++ ./configure --prefix=/usr/local --enable-shared && sudo make install 2>/dev/null)
fold_end hdf5

fold_start netcdf netcdf
curl -L ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz | tar -C /tmp --extract --gunzip --file -
(cd /tmp/netcdf-4.3.3.1 && CC=gcc ./configure && sudo make install 2>/dev/null)
fold_end netcdf

fold_start deps deps
R --no-save -f util/update-dependencies.R --args ./DESCRIPTION.in
fold_end deps

which otool
