#!/bin/bash

set -o errexit

export _R_CHECK_FORCE_SUGGESTS_=false
export OMP_NUM_THREADS=2

fold_start() {
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
}

fold_end() {
  echo -e "\ntravis_fold:end:$1\r"
}

travis_wait() {
    # https://github.com/travis-ci/travis-ci/issues/4190#issuecomment-169987525
    local minutes=0
    local limit=40
    while kill -0 $! >/dev/null 2>&1; do
	echo -n -e " \b" # never leave evidences!
	if [ $minutes == $limit ]; then break; fi
	local minutes=$((minutes+1))
	sleep 60
    done
    wait $! || exit 1
}

#echo "IMX_OPT_ENGINE=$IMX_OPT_ENGINE"
#echo "TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE"

if [ "x$TRAVIS_OS_NAME" = xlinux ]; then
    if [ "x$MODE" = xtest ]; then
	fold_start make.install "make install"
	make install
	fold_end make.install
    fi

    if [ "x$MODE" = xtest ]; then
	make test
    elif [ "x$MODE" = xcran-check ]; then
	make cran-check &
	travis_wait
    fi
elif [ "x$TRAVIS_OS_NAME" = xosx ]; then
    if [ "x$MODE" = xbuild ]; then
	git fetch --unshallow  # need tags to compute version string
	make cran-build
	#make build
	pushd staging && tar zxf OpenMx_*.tgz && popd
	pushd staging/OpenMx/libs && ../../../util/libtastic.py -r -id OpenMx.so /usr/local/ && popd
	pushd staging && tar zcf OpenMx_*.tgz OpenMx && popd
    fi
fi
