#!/bin/bash

set -o errexit

fold_start() {
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
}

fold_end() {
  echo -e "\ntravis_fold:end:$1\r"
}

echo "IMX_OPT_ENGINE=$IMX_OPT_ENGINE"
#echo "TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE"

fold_start make.install "make install"
make install
fold_end make.install

if [ "x$TRAVIS_EVENT_TYPE" = xcron ]; then
    make torture
    make nightly
else
    make test
fi
