#!/bin/bash

set -o errexit

make install

echo "TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE"

if "x$TRAVIS_EVENT_TYPE" = xcron; then
    make torture
    make nightly

    echo "Looks good! Updating stable branch"
    git fetch origin stable
    git checkout -b stable FETCH_HEAD
    git merge --no-ff -m "Nightly tests passed" master
    git push origin HEAD:stable
else
    make test
    make cran-check
fi
