#!/bin/sh

echo "** loading modules"
eval $(modulecmd sh load R gcc git)
echo "** OK"

export EXIT_STATUS=../status
rm -f $EXIT_STATUS
srun -p standard --time=1-12:00:00 --cpus-per-task=4 --pty -u $HOME/bin/test-openmx2 $*
status=$(cat $EXIT_STATUS)
exit $status
