#!/bin/sh
echo "enter test-openmx2"
#SBATCH --partition=standard 
#SBATCH --time=1-12:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4

if [ "x$TMPDIR" != x ]; then
  export R_LIBS_USER="$TMPDIR"/R
fi

echo "launching test-openmx3 $*"
$HOME/bin/test-openmx3 $*

echo $? > ../status
