#!/bin/bash

set -o errexit
set -o nounset

vtemplate=$(grep ^Version ../DESCRIPTION | cut -d' ' -f 2)
short=$(echo -n "$vtemplate" | cut -d- -f 1)
long=$(echo -n "$vtemplate")

cat source/conf.py.in | sed s/@SHORTVERSION@/$short/ | sed s/@LONGVERSION@/$long/ > source/conf.py
