#!/bin/bash

set -o errexit
set -o nounset

vtemplate=$(grep ^Version ../DESCRIPTION | cut -d' ' -f 2)
if [ "x$vtemplate" = x ]; then
  echo "Cannot find verison in ../DESCRIPTION"
  exit 1
fi
short=$(echo -n "$vtemplate" | cut -d- -f 1)
long=$(echo -n "$vtemplate")

cat source/conf.py.in | sed s/@SHORTVERSION@/$short/ | sed s/@LONGVERSION@/$long/ > source/conf.py

perl -pi -e "s,http://openmx.psyc.virginia.edu/docs/OpenMx/latest/,http://openmx.psyc.virginia.edu/docs/OpenMx/$long/," source/*.rst
