require(OpenMx)

A <- mxMatrix(values = runif(25), nrow = 5, ncol = 5, name = 'A')
B <- mxMatrix(values = runif(25), nrow = 5, ncol = 5, name = 'B')

test0 <- mxAlgebra(A, name = 'test0')
test1 <- mxAlgebra(solve(A), name = 'test1')
test2 <- mxAlgebra(t(A), name = 'test2')
test3 <- mxAlgebra(A ^ B, name = 'test3')
test4 <- mxAlgebra(A %*% B, name = 'test4')
test5 <- mxAlgebra(A * B, name = 'test5')
test6 <- mxAlgebra(A %x% B, name = 'test6')
test7 <- mxAlgebra(A %&% B, name = 'test7')
test8 <- mxAlgebra(A / B, name = 'test8')
test9 <- mxAlgebra(A + B, name = 'test9')
test10 <- mxAlgebra(A - B, name = 'test10')
test11 <- mxAlgebra(-A, name = 'test11')
test12 <- mxAlgebra(cbind(A,B), name = 'test12')
test13 <- mxAlgebra(rbind(A,B), name = 'test13')
test14 <- mxAlgebra(det(A), name = 'test14')
test15 <- mxAlgebra(tr(A), name = 'test15')
test16 <- mxAlgebra(sum(A,B), name = 'test16')
test17 <- mxAlgebra(prod(A,B), name = 'test17')
test18 <- mxAlgebra(max(A,B), name = 'test18')
test19 <- mxAlgebra(min(A,B), name = 'test19')
test20 <- mxAlgebra(abs(A), name = 'test20')
test21 <- mxAlgebra(cos(A), name = 'test21')
test22 <- mxAlgebra(cosh(A), name = 'test22')
test23 <- mxAlgebra(sin(A), name = 'test23')
test24 <- mxAlgebra(sinh(A), name = 'test24')
test25 <- mxAlgebra(tan(A), name = 'test25')
test26 <- mxAlgebra(tanh(A), name = 'test26')

model <- mxModel(A,B,
	test0,test1,test2,test3,test4,
	test5,test6,test7,test8,test9,
	test10,test11,test12,test13,test14,
	test15,test16,test17,test18,test19,
	test20,test21,test22,test23,test24,
	test25,test26)

model <- mxRun(model)

omxCheckCloseEnough(model[['test0']]@result, A@values, 0.001)
omxCheckCloseEnough(model[['test1']]@result, solve(A@values), 0.001)
omxCheckCloseEnough(model[['test2']]@result, t(A@values), 0.001)
omxCheckCloseEnough(model[['test3']]@result, A@values ^ B@values, 0.001)
omxCheckCloseEnough(model[['test4']]@result, A@values %*% B@values, 0.001)
omxCheckCloseEnough(model[['test5']]@result, A@values * B@values, 0.001)
omxCheckCloseEnough(model[['test6']]@result, A@values %x% B@values, 0.001)
omxCheckCloseEnough(model[['test7']]@result, A@values %&% B@values, 0.001)
omxCheckCloseEnough(model[['test8']]@result, A@values / B@values, 0.001)
omxCheckCloseEnough(model[['test9']]@result, A@values + B@values, 0.001)
omxCheckCloseEnough(model[['test10']]@result, A@values - B@values, 0.001)
omxCheckCloseEnough(model[['test11']]@result, -A@values, 0.001)
omxCheckCloseEnough(model[['test12']]@result, cbind(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['test13']]@result, rbind(A@values, B@values), 0.001)
#omxCheckCloseEnough(model[['test14']]@result, det(A@values), 0.001)
omxCheckCloseEnough(model[['test15']]@result, tr(A@values), 0.001)
omxCheckCloseEnough(model[['test16']]@result, sum(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['test17']]@result, prod(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['test18']]@result, max(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['test19']]@result, min(A@values, B@values), 0.001)
omxCheckCloseEnough(model[['test20']]@result, abs(A@values), 0.001)
omxCheckCloseEnough(model[['test21']]@result, cos(A@values), 0.001)
omxCheckCloseEnough(model[['test22']]@result, cosh(A@values), 0.001)
omxCheckCloseEnough(model[['test23']]@result, sin(A@values), 0.001)
omxCheckCloseEnough(model[['test24']]@result, sinh(A@values), 0.001)
omxCheckCloseEnough(model[['test25']]@result, tan(A@values), 0.001)
omxCheckCloseEnough(model[['test26']]@result, tanh(A@values), 0.001)
