require(OpenMx)
myLongitudinalData<-read.table("myLongitudinalData.txt",header=T)

model<-mxModel("Linear Growth Curve Model, Matrix Specification", 
      mxData(myLongitudinalData, type="raw"),
      mxMatrix("Full",  nrow=7, ncol=7,
            values=c(0,0,0,0,0,1,0,
                     0,0,0,0,0,1,1,
                     0,0,0,0,0,1,2,
                     0,0,0,0,0,1,3,
                     0,0,0,0,0,1,4,
                     0,0,0,0,0,0,0,
                     0,0,0,0,0,0,0),
            free=F,
            byrow=TRUE,
            name="A"),
      mxMatrix("Symm",  nrow=7, ncol=7,
            values=c(0,0,0,0,0,  0,  0,
                     0,0,0,0,0,  0,  0,
                     0,0,0,0,0,  0,  0,
                     0,0,0,0,0,  0,  0,
                     0,0,0,0,0,  0,  0,
                     0,0,0,0,0,  1,0.5,
                     0,0,0,0,0,0.5,  1),
            free=c(T, F,F,F,F,F,F,
                   F,T, F,F,F,F,F,
                   F,F,T, F,F,F,F,
                   F,F,F,T, F,F,F,
                   F,F,F,F,T, F,F,
                   F,F,F,F,F,T, T,
                   F,F,F,F,F,T, T),
            labels=c("residual",NA,NA,NA,NA,NA,NA,
                     NA,"residual",NA,NA,NA,NA,NA,
                     NA,NA,"residual",NA,NA,NA,NA,
                     NA,NA,NA,"residual",NA,NA,NA,
                     NA,NA,NA,NA,"residual",NA,NA,
                     NA,NA,NA,NA,NA,"vari","cov",
                     NA,NA,NA,NA,NA,"cov","vars"),
            byrow= TRUE,
            name="S"),
      mxMatrix("Full",  nrow=5, ncol=7,
            values=c(1,0,0,0,0,0,0,
                     0,1,0,0,0,0,0,
                     0,0,1,0,0,0,0,
                     0,0,0,1,0,0,0,
                     0,0,0,0,1,0,0),
            free=F,
            byrow=T,
            name="F"),
      mxMatrix("Full",  nrow=1, ncol=7,
            values=c(0,0,0,0,0,1,1),
            free=c(F,F,F,F,F,T,T),
            labels=c(NA,NA,NA,NA,NA,"meani","means"),
            name="M"),
      mxRAMObjective("A","S","F","M")
      )
