require(OpenMx)
myFADataRaw<-read.table("myFAData.txt", header=T)

myFADataRaw<-myFADataRaw[,c("x1","x2","x3","y1","y2","y3")]

model<-mxModel("Two Factor Model - Matrix Specification", 
      mxData(myFADataRaw, type="raw"),
      mxMatrix("Full", nrow=8, ncol=8,
            values=c(0,0,0,0,0,0,1,0,
                     0,0,0,0,0,0,1,0,
                     0,0,0,0,0,0,1,0,
                     0,0,0,0,0,0,0,1,
                     0,0,0,0,0,0,0,1,
                     0,0,0,0,0,0,0,1,
                     0,0,0,0,0,0,0,0,
                     0,0,0,0,0,0,0,0),
            free=c(F, F, F, F, F, F, F, F,
                   F, F, F, F, F, F, T, F,
                   F, F, F, F, F, F, T, F,
                   F, F, F, F, F, F, F, F,
                   F, F, F, F, F, F, F, T,
                   F, F, F, F, F, F, F, T,
                   F, F, F, F, F, F, F, F,
                   F, F, F, F, F, F, F, F),
            labels=c(NA,NA,NA,NA,NA,NA,"l1", NA,
                     NA,NA,NA,NA,NA,NA,"l2", NA,
                     NA,NA,NA,NA,NA,NA,"l3", NA,
                     NA,NA,NA,NA,NA,NA, NA,"l4",
                     NA,NA,NA,NA,NA,NA, NA,"l5",
                     NA,NA,NA,NA,NA,NA, NA,"l6",
                     NA,NA,NA,NA,NA,NA, NA, NA,
                     NA,NA,NA,NA,NA,NA, NA, NA),
            byrow=TRUE,
            name="A"),
      mxMatrix("Symm", nrow=8, ncol=8, 
            values=c(1,0,0,0,0,0, 0, 0,
                     0,1,0,0,0,0, 0, 0,
                     0,0,1,0,0,0, 0, 0,
                     0,0,0,1,0,0, 0, 0,
                     0,0,0,0,1,0, 0, 0,
                     0,0,0,0,0,1, 0, 0,
                     0,0,0,0,0,0, 1,.5,
                     0,0,0,0,0,0,.5, 1),
            free=c(T, F, F, F, F, F, F, F,
                   F, T, F, F, F, F, F, F,
                   F, F, T, F, F, F, F, F,
                   F, F, F, T, F, F, F, F,
                   F, F, F, F, T, F, F, F,
                   F, F, F, F, F, T, F, F,
                   F, F, F, F, F, F, T, T,
                   F, F, F, F, F, F, T, T),
            labels=c("e1", NA,   NA,   NA,   NA,   NA,    NA,    NA,
                     NA, "e2",   NA,   NA,   NA,   NA,    NA,    NA,
                     NA,   NA, "e3",   NA,   NA,   NA,    NA,    NA,
                     NA,   NA,   NA, "e4",   NA,   NA,    NA,    NA,
                     NA,   NA,   NA,   NA, "e5",   NA,    NA,    NA,
                     NA,   NA,   NA,   NA,   NA, "e6",    NA,    NA,
                     NA,   NA,   NA,   NA,   NA,   NA, "varF1", "cov",
                     NA,   NA,   NA,   NA,   NA,   NA, "cov", "varF2"),
            byrow=TRUE,
            name="S"),
      mxMatrix("Full",  nrow=6, ncol=8,
            free=F,
            values=c(1,0,0,0,0,0,0,0,
                     0,1,0,0,0,0,0,0,
                     0,0,1,0,0,0,0,0,
                     0,0,0,1,0,0,0,0,
                     0,0,0,0,1,0,0,0,
                     0,0,0,0,0,1,0,0),
            byrow=T,
            name="F"),
      mxMatrix("Full", nrow=1, ncol=8,
            values=c(1,1,1,1,1,1,0,0),
            free=c(T,T,T,T,T,T,F,F),
            labels=c("meanx1","meanx2","meanx3",
                     "meanx4","meanx5","meanx6",
                     NA,NA),
            name="M"),
      mxRAMObjective("A","S","F","M")
      )
      
twoFactorMatrixRaw<-mxRun(model)
